name: par2cmdline CI build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: automake
      run: ./automake.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    #- name: make distcheck ## maybe later, currently testing around
      #run: make distcheck

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build
      run: msbuild -property:Configuration=Release -property:Platform=x64 par2cmdline.sln
